[workspace]
members = [
    "crates/nh-api",
    "crates/nh-bridge",
    "crates/nh-download",
    "crates/nh-storage",
    "crates/nh-tests",
]
resolver = "2"

[workspace.lints.clippy]
nursery = { level = "warn", priority = -1 }
unwrap_used = "warn"
panic = "warn"
clone_on_copy = "warn"
redundant_closure_for_method_calls = "warn"
needless_return = "warn"
wildcard_imports = "warn"

[workspace.lints.rust]
unused_variables = "warn"
unused_imports = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }