// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `api_client`, `gallery_detail_to_info`, `gallery_list_to_preview`, `storage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `init_bridge_with_config`

/// Initialise the bridge layer — call once from Dart during app startup.
Future<void> initBridge({required Storage storage}) =>
    RustLib.instance.api.crateApiGalleryInitBridge(storage: storage);

Future<void> nhSetApiKey({required String apiKey}) =>
    RustLib.instance.api.crateApiGalleryNhSetApiKey(apiKey: apiKey);

Future<String> nhGetApiKey() =>
    RustLib.instance.api.crateApiGalleryNhGetApiKey();

/// Warm up the connection by visiting the main page.
Future<int> nhWarmUp() => RustLib.instance.api.crateApiGalleryNhWarmUp();

/// Fetch a gallery by ID (cache-first strategy).
Future<GalleryInfo> nhGetGallery({required BigInt id}) =>
    RustLib.instance.api.crateApiGalleryNhGetGallery(id: id);

/// Search galleries by query string.
Future<List<GalleryPreviewInfo>> nhSearchGalleries({
  required String query,
  required int page,
}) => RustLib.instance.api.crateApiGalleryNhSearchGalleries(
  query: query,
  page: page,
);

/// Get popular galleries.
Future<List<GalleryPreviewInfo>> nhGetPopular() =>
    RustLib.instance.api.crateApiGalleryNhGetPopular();

/// Get a random gallery ID.
Future<BigInt> nhGetRandom() =>
    RustLib.instance.api.crateApiGalleryNhGetRandom();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Storage>>
abstract class Storage implements RustOpaqueInterface {}

/// Full gallery info exposed to Dart.
class GalleryInfo {
  final BigInt id;
  final String mediaId;
  final String? titleEn;
  final String? titleJp;
  final String? titlePretty;
  final int numPages;
  final int numFavorites;
  final String? coverUrl;
  final String? thumbnailUrl;
  final List<TagInfo> tags;

  const GalleryInfo({
    required this.id,
    required this.mediaId,
    this.titleEn,
    this.titleJp,
    this.titlePretty,
    required this.numPages,
    required this.numFavorites,
    this.coverUrl,
    this.thumbnailUrl,
    required this.tags,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      mediaId.hashCode ^
      titleEn.hashCode ^
      titleJp.hashCode ^
      titlePretty.hashCode ^
      numPages.hashCode ^
      numFavorites.hashCode ^
      coverUrl.hashCode ^
      thumbnailUrl.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          mediaId == other.mediaId &&
          titleEn == other.titleEn &&
          titleJp == other.titleJp &&
          titlePretty == other.titlePretty &&
          numPages == other.numPages &&
          numFavorites == other.numFavorites &&
          coverUrl == other.coverUrl &&
          thumbnailUrl == other.thumbnailUrl &&
          tags == other.tags;
}

/// Lightweight preview for list views.
class GalleryPreviewInfo {
  final BigInt id;
  final String title;
  final int numPages;
  final String? coverUrl;

  const GalleryPreviewInfo({
    required this.id,
    required this.title,
    required this.numPages,
    this.coverUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ numPages.hashCode ^ coverUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryPreviewInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          numPages == other.numPages &&
          coverUrl == other.coverUrl;
}

/// Tag info for Dart.
class TagInfo {
  final BigInt id;
  final String tagType;
  final String name;
  final String url;
  final BigInt count;

  const TagInfo({
    required this.id,
    required this.tagType,
    required this.name,
    required this.url,
    required this.count,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      tagType.hashCode ^
      name.hashCode ^
      url.hashCode ^
      count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          tagType == other.tagType &&
          name == other.name &&
          url == other.url &&
          count == other.count;
}
