// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `api_client`, `cached_to_info`, `gallery_to_info`, `preview_to_info`, `storage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Initialise the bridge layer — call once from Dart during app startup.
Future<void> initBridge({required Storage storage}) =>
    RustLib.instance.api.crateApiGalleryInitBridge(storage: storage);

/// Fetch a gallery by ID.
///
/// Strategy: look in local cache first; on miss, fetch from the remote API
/// and persist the result for next time.
Future<GalleryInfo> nhGetGallery({required BigInt id}) =>
    RustLib.instance.api.crateApiGalleryNhGetGallery(id: id);

/// Search galleries by query string.
///
/// Fetches results from the remote API.
Future<List<GalleryPreviewInfo>> nhSearchGalleries({
  required String query,
  required int page,
}) => RustLib.instance.api.crateApiGalleryNhSearchGalleries(
  query: query,
  page: page,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Storage>>
abstract class Storage implements RustOpaqueInterface {}

/// Full gallery info exposed to Dart.
class GalleryInfo {
  final BigInt id;
  final String mediaId;
  final String? titleEn;
  final String? titleJp;
  final String? titlePretty;
  final int numPages;
  final int numFavorites;
  final String? coverExt;
  final String? coverUrl;
  final String? thumbnailUrl;

  const GalleryInfo({
    required this.id,
    required this.mediaId,
    this.titleEn,
    this.titleJp,
    this.titlePretty,
    required this.numPages,
    required this.numFavorites,
    this.coverExt,
    this.coverUrl,
    this.thumbnailUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      mediaId.hashCode ^
      titleEn.hashCode ^
      titleJp.hashCode ^
      titlePretty.hashCode ^
      numPages.hashCode ^
      numFavorites.hashCode ^
      coverExt.hashCode ^
      coverUrl.hashCode ^
      thumbnailUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          mediaId == other.mediaId &&
          titleEn == other.titleEn &&
          titleJp == other.titleJp &&
          titlePretty == other.titlePretty &&
          numPages == other.numPages &&
          numFavorites == other.numFavorites &&
          coverExt == other.coverExt &&
          coverUrl == other.coverUrl &&
          thumbnailUrl == other.thumbnailUrl;
}

/// Lightweight preview for list views.
class GalleryPreviewInfo {
  final BigInt id;
  final String title;
  final int numPages;
  final String? coverExt;
  final String? coverUrl;

  const GalleryPreviewInfo({
    required this.id,
    required this.title,
    required this.numPages,
    this.coverExt,
    this.coverUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      numPages.hashCode ^
      coverExt.hashCode ^
      coverUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GalleryPreviewInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          numPages == other.numPages &&
          coverExt == other.coverExt &&
          coverUrl == other.coverUrl;
}
