[package]
name = "nh-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
nh-api = { path = "../nh-api" }
nh-bridge = { path = "../nh-bridge", package = "rust_lib_nh_flutter_ui" }
nh-download = { path = "../nh-download" }
nh-storage = { path = "../nh-storage" }

serde_json = "1.0"
reqwest = { version = "0.12", features = ["native-tls", "json", "gzip", "brotli"] }
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
anyhow = "1"

[lints]
workspace = true